'''High-level project builder.

`build_project(program, project_name, ...)` runs the full pipeline in
one call:

  Program → HIR → MIR
         → emit per-rule complete runner structs
         → compute schema definitions + DB blueprint alias
         → write the .cpp tree to ~/.cache/srdatalog/jit/<project>_<hash>/

Returns the same dict as `cache.write_jit_project`.

The resulting `jit_batch_N.cpp` files are byte-identical to what Nim's
codegen writes to its own JIT cache — they self-contain the schema +
DB type alias, so the same compile flags / external deps that work
for Nim's output work here too.
'''
from __future__ import annotations

from typing import TYPE_CHECKING

from srdatalog.codegen.batchfile import _collect_pipelines
from srdatalog.codegen.jit.cache import write_jit_project
from srdatalog.codegen.jit.complete_runner import gen_complete_runner
from srdatalog.codegen.jit.main_file import (
  gen_db_type_alias_for_batch,
  gen_main_file_content,
  gen_schema_definitions_for_batch,
)
from srdatalog.codegen.jit.orchestrator_jit import gen_step_body
from srdatalog.hir import compile_to_hir, compile_to_mir

if TYPE_CHECKING:
  from srdatalog.dsl import Program


def build_project(
  program: "Program",
  project_name: str,
  *,
  cache_base: str | None = None,
  emit_main_file: bool = True,
) -> dict[str, object]:
  '''Compile `program` end-to-end and write the .cpp tree.

  Args:
    program: a `srdatalog.Program` (DSL output).
    project_name: human-readable name used in C++ identifiers + cache
      dir. The C++ side derives `<project>_DB`, `<project>_DB_Blueprint`,
      `<project>_DB_DeviceDB`, and the cache lives at
      `~/.cache/srdatalog/jit/<project>_DB_<hash>/`.
    cache_base: override `~/.cache/srdatalog` (e.g., a tmpdir for
      tests, or `./build` for an in-tree project layout).
    emit_main_file: if True, also write a `main.cpp` containing the
      `_Runner` struct + relation typedefs. Set False if you only want
      the batch files (e.g., when integrating with an existing host
      binary that defines its own `<Project>_Runner`).

  Returns the dict from `cache.write_jit_project`:
    { "dir", "main", "batches": [...], "schema_header", "kernel_header" }
  '''
  hir = compile_to_hir(program)
  mir = compile_to_mir(program)

  # The C++ side calls the device-DB type `<project>_DB_DeviceDB`.
  # See main_file.gen_db_type_alias_for_batch — the `ruleset_name`
  # arg there is the ext_db name (`<project>_DB`).
  ext_db = f"{project_name}_DB"
  device_db = f"{ext_db}_DeviceDB"

  # Per-step bodies (orchestrator) + per-rule complete runner (kernel
  # struct, phase methods, execute()).
  step_bodies = [
    gen_step_body(step, device_db, is_rec, i)
    for i, (step, is_rec) in enumerate(mir.steps)
  ]
  per_rule: list[tuple[str, str]] = []
  runner_decls: dict[str, str] = {}
  for ep in _collect_pipelines(mir):
    decl, full = gen_complete_runner(ep, device_db)
    per_rule.append((ep.rule_name, full))
    runner_decls[ep.rule_name] = decl

  # Compute the inlined schema + DB strings — these get prepended to
  # every batch file by JitBatchManager so the batches compile in
  # isolation.
  schema_defs = gen_schema_definitions_for_batch(hir.relation_decls)
  db_alias = gen_db_type_alias_for_batch(ext_db, hir.relation_decls)

  # Optional standalone main file (Python-only convenience — Nim's
  # main is the user's `.nim` file, not generated by codegen).
  main_cpp = ""
  if emit_main_file:
    main_cpp = gen_main_file_content(
      project_name, hir.relation_decls, mir, step_bodies, runner_decls,
      cache_dir_hint="<cache>", jit_batch_count=1,
    )

  return write_jit_project(
    ext_db,
    main_file_content=main_cpp,
    per_rule_runners=per_rule,
    schema_definitions=schema_defs,
    db_type_alias=db_alias,
    cache_base=cache_base,
  )
