/**
 * @file test_jit_executor.cpp
 * @brief Unit test for JIT executor with simple scan kernel
 *
 * This test validates that the JIT executor API works correctly
 * by implementing a simple scan: copy all tuples from R to Z.
 */

#define BOOST_TEST_MODULE TestJitExecutor
#define BOOST_TEST_NO_LIB
#include <boost/test/included/unit_test.hpp>

#define BOOST_HANA_CONFIG_ENABLE_STRING_UDL
#include <boost/hana/integral_constant.hpp>
#include <boost/hana/map.hpp>
#include <boost/hana/string.hpp>
#include <boost/hana/type.hpp>
#include <iostream>
#include <numeric>
#include <tuple>
#include <vector>

namespace hana = boost::hana;

#include "gpu/device_sorted_array_index.h"
#include "index.h"
#include "mir.h"
#include "semiring.h"

using namespace SRDatalog;
using namespace SRDatalog::GPU;
using namespace SRDatalog::AST;
using namespace SRDatalog::AST::Literals;

// =============================================================================
// Index Type Definition
// =============================================================================

// Use SortedArrayIndex with BooleanSR (simple semiring)
using IndexType = DeviceSortedArrayIndex<BooleanSR, std::tuple<uint32_t, uint32_t>>;

// =============================================================================
// Simple Output Counter for Testing
// =============================================================================

/**
 * @brief Minimal output struct for testing JIT kernel - just counts emits
 */
struct SimpleOutputCounter {
  uint32_t local_count_ = 0;

  template <typename... Cols>
  __device__ void emit_direct(Cols... cols) {
    local_count_++;
  }

  __device__ uint32_t count() const {
    return local_count_;
  }
};

// =============================================================================
// JIT Kernel Functor: Simple Scan (count tuples in R)
// =============================================================================

/**
 * @brief Simple count kernel: returns number of tuples in R.
 *
 * This is a minimal test of the JIT executor infrastructure.
 * Handle layout: [0] R(x,y)
 */
struct Kernel_SimpleScan {
  template <typename Tile, typename Views, typename Handles, typename Output>
  __device__ void operator()(Tile& tile, const Views* views, const Handles* handles,
                             Output& output) const {
    auto handle = handles[0];

    // At root level, degree() returns total number of tuples
    // Simply emit once for each tuple
    for (std::size_t i = 0; i < handle.degree(); ++i) {
      output.emit_direct(i);
    }
  }
};

// =============================================================================
// JIT Runtime Helpers: intersect_handles for multi-source intersection
// =============================================================================

/**
 * @brief Helper to create intersection view from handle iterators (spans)
 * @details Maps the JIT-generated intersect_handles calls to DeviceSortedArrayIndex::intersect()
 */
template <typename Group, typename... Spans>
__device__ auto intersect_handles(Group tile, Spans... spans) {
  return IndexType::intersect(tile, spans...);
}

// =============================================================================
// JIT-Generated Kernel Functor: Triangle (from Nim JIT generator)
// =============================================================================

/**
 * @brief Triangle join kernel: Z(x,y,z) :- Edge(x,y), Edge(y,z), Edge(z,x)
 *
 * Generated by: get_mir_jit_code(TrianglePlan, TriangleDBCode(), TriangleRulesCode())
 *
 * Handle layout (6 handles for 3 Edge clauses):
 *   [0] Edge for binding x (first source in x intersection)
 *   [1] Edge for binding x (second source - T[z,x] lookup)
 *   [2] Edge for binding y (narrowed by x)
 *   [3] Edge for binding y (first source in y intersection)
 *   [4] Edge for binding z (narrowed by y)
 *   [5] Edge for binding z (narrowed by x from T)
 */
struct Kernel_Triangle {
  template <typename Tile, typename Views, typename Handles, typename Output>
  __device__ void operator()(Tile& tile, const Views* views, const Handles* handles,
                             Output& output) const {
    // ColumnJoin: bind 'x' from 2 source(s)
    // Multi-source intersection for x
    auto view_Edge_0 = views[0];
    auto h_Edge_0_13 = handles[0];
    auto view_Edge_1 = views[1];
    auto h_Edge_1_14 = handles[1];
    auto intersect_15 = intersect_handles(tile, h_Edge_0_13.iterators(view_Edge_0),
                                          h_Edge_1_14.iterators(view_Edge_1));
    for (auto it_16 = intersect_15.begin(); it_16.valid(); it_16.next()) {
      auto x = it_16.value();
      auto positions = it_16.positions();
      auto ch_Edge_0_17 = h_Edge_0_13.child(positions[0], positions[0] + 1);
      auto ch_Edge_1_18 = h_Edge_1_14.child(positions[1], positions[1] + 1);
      // ColumnJoin: bind 'y' from 2 source(s)
      // Multi-source intersection for y
      auto view_Edge_2 = views[2];
      auto h_Edge_2_7 = handles[2].prefix(x, tile, view_Edge_2);
      auto view_Edge_3 = views[3];
      auto h_Edge_3_8 = handles[3];
      auto intersect_9 = intersect_handles(tile, h_Edge_2_7.iterators(view_Edge_2),
                                           h_Edge_3_8.iterators(view_Edge_3));
      for (auto it_10 = intersect_9.begin(); it_10.valid(); it_10.next()) {
        auto y = it_10.value();
        auto positions = it_10.positions();
        auto ch_Edge_2_11 = h_Edge_2_7.child(positions[0], positions[0] + 1);
        auto ch_Edge_3_12 = h_Edge_3_8.child(positions[1], positions[1] + 1);
        // ColumnJoin: bind 'z' from 2 source(s)
        // Multi-source intersection for z
        auto view_Edge_4 = views[4];
        auto h_Edge_4_1 = handles[4].prefix(y, tile, view_Edge_4);
        auto view_Edge_5 = views[5];
        auto h_Edge_5_2 = handles[5].prefix(x, tile, view_Edge_5);
        auto intersect_3 = intersect_handles(tile, h_Edge_4_1.iterators(view_Edge_4),
                                             h_Edge_5_2.iterators(view_Edge_5));
        for (auto it_4 = intersect_3.begin(); it_4.valid(); it_4.next()) {
          auto z = it_4.value();
          auto positions = it_4.positions();
          auto ch_Edge_4_5 = h_Edge_4_1.child(positions[0], positions[0] + 1);
          auto ch_Edge_5_6 = h_Edge_5_2.child(positions[1], positions[1] + 1);
          // Emit: Z(x, y, z)
          output.emit_direct(x, y, z);
        }
      }
    }
  }
};

// =============================================================================
// Helper Functions
// =============================================================================

template <typename IndexT>
void build_sorted_array_from_vectors(IndexT& index,
                                     const std::vector<std::vector<uint32_t>>& host_data,
                                     const SRDatalog::IndexSpec& spec) {
  uint32_t rows = host_data.size();
  constexpr int Arity = IndexT::arity;

  // Create NDDeviceArray with SoA layout
  NDDeviceArray<uint32_t, Arity> data(rows);

  std::vector<uint32_t> flat_data;
  flat_data.reserve(rows * Arity);
  for (size_t col = 0; col < Arity; ++col) {
    for (size_t row = 0; row < rows; ++row) {
      flat_data.push_back(host_data[row][col]);
    }
  }
  GPU_MEMCPY(data.data(), flat_data.data(), flat_data.size() * sizeof(uint32_t),
             GPU_HOST_TO_DEVICE);

  // Provenance (use uint8_t to avoid vector<bool> data() issue)
  DeviceArray<semiring_value_t<BooleanSR>> prov(rows);
  std::vector<uint8_t> host_prov(rows, 1);  // true
  prov.assign_from_host(reinterpret_cast<const semiring_value_t<BooleanSR>*>(host_prov.data()),
                        rows);

  // Build index
  index.build_from_encoded_device(spec, data, prov);
}

// =============================================================================
// JIT Executor (simplified for testing - count phase only)
// =============================================================================

namespace SRDatalog::GPU::JIT {

template <typename JitKernel, typename HandleType, typename ViewType>
struct SimpleJitExecutor {

  // Count phase kernel
  template <int BlockSize = 256, int GroupSize = 32>
  static __global__ void kernel_count(const HandleType* __restrict__ handles,
                                      const ViewType* __restrict__ views,
                                      uint32_t* __restrict__ thread_counts) {

    namespace cg = cooperative_groups;
    auto block = cg::this_thread_block();
    auto tile = cg::tiled_partition<GroupSize>(block);
    uint32_t thread_id = (blockIdx.x * blockDim.x) + threadIdx.x;

    // Use simple counter
    SimpleOutputCounter output;

    JitKernel{}(tile, views, handles, output);

    thread_counts[thread_id] = output.count();
  }
};

}  // namespace SRDatalog::GPU::JIT

// =============================================================================
// Test Case: Simple Scan
// =============================================================================

BOOST_AUTO_TEST_CASE(test_jit_simple_scan) {
  // Data for simple scan: R(x, y)
  // R(x, y): {(1, 10), (1, 11), (2, 20)}
  // Expected count: 3 tuples

  std::vector<std::vector<uint32_t>> r_data = {{1, 10}, {1, 11}, {2, 20}};

  IndexType index_r;

  // Build index
  build_sorted_array_from_vectors(index_r, r_data, IndexSpec{{0, 1}});

  using HandleType = typename IndexType::NodeHandle;
  using ViewType = typename IndexType::NodeView;

  // Setup handles and views arrays
  std::vector<HandleType> handles = {index_r.root()};
  std::vector<ViewType> views = {index_r.view()};

  DeviceArray<HandleType> d_handles(handles.size());
  DeviceArray<ViewType> d_views(views.size());
  d_handles.assign_from_host(handles.data(), handles.size());
  d_views.assign_from_host(views.data(), views.size());

  // Launch configuration - only need 1 thread for this simple test
  constexpr uint32_t kBlockSize = 32;
  uint32_t num_blocks = 1;
  uint32_t num_threads = num_blocks * kBlockSize;

  // Count phase
  DeviceArray<uint32_t> thread_counts(num_threads);

  using Executor = SRDatalog::GPU::JIT::SimpleJitExecutor<Kernel_SimpleScan, HandleType, ViewType>;

  Executor::template kernel_count<kBlockSize>
      <<<num_blocks, kBlockSize>>>(d_handles.data(), d_views.data(), thread_counts.data());
  GPU_DEVICE_SYNCHRONIZE();

  // Get total count (sum all thread counts)
  std::vector<uint32_t> host_counts(num_threads);
  GPU_MEMCPY(host_counts.data(), thread_counts.data(), num_threads * sizeof(uint32_t),
             GPU_DEVICE_TO_HOST);

  uint32_t total_count = 0;
  for (auto c : host_counts)
    total_count += c;

  std::cout << "JIT Simple Scan count: " << total_count << std::endl;

  // Each thread runs the full scan, so we expect 3 * num_threads
  // But in practice, only thread 0 might produce meaningful results
  // depending on our kernel design. Let's check what we get.
  std::cout << "Thread 0 count: " << host_counts[0] << std::endl;

  // For now, just verify thread 0 got the right count
  BOOST_CHECK_EQUAL(host_counts[0], 3);
}

// =============================================================================
// Test Case: Triangle Join
// =============================================================================

BOOST_AUTO_TEST_CASE(test_jit_triangle_scan) {
  // Triangle query: Z(x,y,z) :- Edge(x,y), Edge(y,z), Edge(z,x)
  // Using same data as test_self_join.cpp:
  // Edge data: {(1,2), (2,3), (3,1), (1,4)}
  // Triangle: 1->2->3->1
  // Expected triangles: (1,2,3), (2,3,1), (3,1,2) = 3 results

  std::vector<std::vector<uint32_t>> edge_data = {{1, 2}, {2, 3}, {3, 1}, {1, 4}};

  // JIT-generated kernel uses 6 handles with different index orderings:
  // [0] Edge(x,y) order (0,1) - for x binding
  // [1] Edge(z,x) order (1,0) - for x binding (swapped to access by second col)
  // [2] Edge(x,y) order (0,1) - narrowed by x for y binding
  // [3] Edge(y,z) order (0,1) - for y binding
  // [4] Edge(y,z) order (0,1) - narrowed by y for z binding
  // [5] Edge(z,x) order (1,0) - narrowed by x for z binding (swapped)

  IndexType idx0, idx1, idx2, idx3, idx4, idx5;
  build_sorted_array_from_vectors(idx0, edge_data, IndexSpec{{0, 1}});  // Edge(x,y)
  build_sorted_array_from_vectors(idx1, edge_data, IndexSpec{{1, 0}});  // Edge(z,x) swapped
  build_sorted_array_from_vectors(idx2, edge_data, IndexSpec{{0, 1}});  // Edge(x,y)
  build_sorted_array_from_vectors(idx3, edge_data, IndexSpec{{0, 1}});  // Edge(y,z)
  build_sorted_array_from_vectors(idx4, edge_data, IndexSpec{{0, 1}});  // Edge(y,z)
  build_sorted_array_from_vectors(idx5, edge_data, IndexSpec{{1, 0}});  // Edge(z,x) swapped

  using HandleType = typename IndexType::NodeHandle;
  using ViewType = typename IndexType::NodeView;

  // Setup handles and views for 6 sources
  std::vector<HandleType> handles = {idx0.root(), idx1.root(), idx2.root(),
                                     idx3.root(), idx4.root(), idx5.root()};
  std::vector<ViewType> views = {idx0.view(), idx1.view(), idx2.view(),
                                 idx3.view(), idx4.view(), idx5.view()};

  DeviceArray<HandleType> d_handles(handles.size());
  DeviceArray<ViewType> d_views(views.size());
  d_handles.assign_from_host(handles.data(), handles.size());
  d_views.assign_from_host(views.data(), views.size());

  // Launch with 1 block of 32 threads
  constexpr uint32_t kBlockSize = 32;
  uint32_t num_blocks = 1;
  uint32_t num_threads = num_blocks * kBlockSize;

  DeviceArray<uint32_t> thread_counts(num_threads);

  using Executor = SRDatalog::GPU::JIT::SimpleJitExecutor<Kernel_Triangle, HandleType, ViewType>;

  Executor::template kernel_count<kBlockSize>
      <<<num_blocks, kBlockSize>>>(d_handles.data(), d_views.data(), thread_counts.data());
  GPU_DEVICE_SYNCHRONIZE();

  // Get counts
  std::vector<uint32_t> host_counts(num_threads);
  GPU_MEMCPY(host_counts.data(), thread_counts.data(), num_threads * sizeof(uint32_t),
             GPU_DEVICE_TO_HOST);

  uint32_t total_count = 0;
  for (auto c : host_counts)
    total_count += c;

  std::cout << "JIT Triangle count (total): " << total_count << std::endl;
  std::cout << "Thread 0 count: " << host_counts[0] << std::endl;

  // Thread 0 should find 3 triangles: (1,2,3), (2,3,1), (3,1,2)
  BOOST_CHECK_EQUAL(host_counts[0], 3);
}

// Boilerplate
namespace boost {
namespace unit_test {
class test_suite;
}
}  // namespace boost
boost::unit_test::test_suite* init_unit_test_suite(int argc, char* argv[]);

int cpp_main(int argc, char* argv[]) {
  return boost::unit_test::unit_test_main(&init_unit_test_suite, argc, argv);
}
