'''Mid-level IR (MIR) types — Phase A: Op-subclassed, frozen+slots.

Per docs/phase_a_mir_onto_op.md (Layer 0 redesign package). All MIR
types are now:

  - `@dataclass(frozen=True, slots=True)` — IR field reassignment
    blocked. List contents remain mutable (back-compat with the
    existing pass shape; A2 introduces tuple coercion + true
    immutability).
  - Subclass `Op` from `srdatalog.ir.core` — walkable by the
    framework's `apply_rewrites_to_fixpoint` and `LoweringPass`
    dispatcher.

ExecutePipeline gains a `pragmas: tuple[tuple[str, Any], ...]` field
(open key/value list — typed as tuple from the start since it's a
new field). The existing named bool fields (`dedup_hash`,
`work_stealing`, `block_group`, `use_fan_out`, `count`,
`concurrent_write`) stay for back-compat through Phase A; Phase A3
removes them and the Phase C `MirPragmaPass` consumes only `pragmas`.

Mapping to Nim (unchanged):
  moColumnSource         -> ColumnSource
  moScan                 -> Scan
  moColumnJoin           -> ColumnJoin
  moCartesianJoin        -> CartesianJoin
  moFilter               -> Filter
  moNegation             -> Negation
  moInsertInto           -> InsertInto
  moExecutePipeline      -> ExecutePipeline
  moRebuildIndex         -> RebuildIndex
  moClearRelation        -> ClearRelation
  moCheckSize            -> CheckSize
  moComputeDelta         -> ComputeDelta
  moComputeDeltaIndex    -> ComputeDeltaIndex
  moMergeIndex           -> MergeIndex
  moMergeRelation        -> MergeRelation
  moRebuildIndexFromIndex -> RebuildIndexFromIndex
  moFixpointPlan         -> FixpointPlan
  moBlock                -> Block
  moProgram              -> Program
'''

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Union, final

from srdatalog.ir.core import Op
from srdatalog.ir.hir.types import Version

# -----------------------------------------------------------------------------
# Leaf / pipeline ops
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ColumnSource(Op):
  '''(column-source #:index (Rel cols...) #:ver V #:prefix (vars))'''

  rel_name: str
  version: Version
  index: list[int]  # column order
  prefix_vars: list[str] = field(default_factory=list)
  handle_start: int = -1  # codegen-internal; not emitted
  clause_idx: int = -1  # origin clause index (post-reorder pass)


@dataclass(frozen=True, slots=True)
class Scan(Op):
  '''(scan #:vars (...) #:index (Rel cols...) #:ver V #:prefix (...))'''

  vars: list[str]
  rel_name: str
  version: Version
  index: list[int]
  prefix_vars: list[str] = field(default_factory=list)
  handle_start: int = -1


@dataclass(frozen=True, slots=True)
class ColumnJoin(Op):
  '''(column-join #:var x #:sources (...))'''

  var_name: str
  sources: list[ColumnSource]
  handle_start: int = -1


@dataclass(frozen=True, slots=True)
class CartesianJoin(Op):
  '''(cartesian-join #:vars (...) #:var-from-source ((...)) #:sources (...))'''

  vars: list[str]
  sources: list[ColumnSource]
  var_from_source: list[list[str]] = field(default_factory=list)
  handle_start: int = -1


@dataclass(frozen=True, slots=True)
class Filter(Op):
  '''(filter #:vars (...) #:code "...")'''

  vars: list[str]
  code: str


@dataclass(frozen=True, slots=True)
class ConstantBind(Op):
  '''(constant-bind #:var v #:code "..." #:deps (...))

  Generated by head-constant rewriting: a HIR LetClause lowers to this
  MIR node, which binds `var_name` to `code` once `deps` are bound.
  '''

  var_name: str
  code: str
  deps: list[str]


@dataclass(frozen=True, slots=True)
class Aggregate(Op):
  '''(aggregate #:var cnt #:func AggCount #:index (Rel 0 1) #:ver FULL #:prefix (x y))

  Aggregation body clause lowered to MIR. `result_var` is the variable
  bound by the aggregate; `agg_func` is the C++ aggregation type
  (AggCount / AggSum / ... / custom). `prefix_vars` are join-prefix
  vars read by the aggregate's index lookup.
  '''

  result_var: str
  agg_func: str
  rel_name: str
  version: Version
  index: list[int]
  prefix_vars: list[str] = field(default_factory=list)
  handle_start: int = -1


@dataclass(frozen=True, slots=True)
class CreateFlatView(Op):
  '''(create-flat-view #:schema R #:index (cols...) #:ver V)

  Emitted by split-rule lowering to expose temp-relation intern columns
  as an unsorted view (avoids a GPU sort between Pipeline A and B).
  '''

  rel_name: str
  version: Version
  index: list[int]


@dataclass(frozen=True, slots=True)
class InnerPipeline(Op):
  '''(inner-pipeline #:rule R #:bound-vars (...) #:handles (...) #:ops (...))

  JIT-generated inner device function for nested joins (Level 2+).
  Nim emits an explicit C++ functor rather than recursive template
  metaprogramming.
  '''

  rule_name: str
  input_handles: list[MirNode] = field(default_factory=list)
  inner_ops: list[MirNode] = field(default_factory=list)
  bound_vars: list[str] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class ProbeJoin(Op):
  '''(probe-join ...) — binary-join mode node. Performs a binary-search
  probe of `probe_rel` keyed on `join_key`, writing row-id pairs into
  `output_buffer`. Uses merge-path balancing for unbalanced output.
  '''

  probe_rel: str
  probe_version: Version
  probe_index: list[int]
  join_key: str
  input_buffer: str = ''  # empty for the first join in a pipeline
  output_buffer: str = ''


@dataclass(frozen=True, slots=True)
class GatherColumn(Op):
  '''(gather-column ...) — binary-join mode node. Dereferences
  `input_buffer` of row IDs into values of `column` from
  `rel_name`, binding the result to `output_var`.
  '''

  rel_name: str
  rel_version: Version
  column: int
  output_var: str
  input_buffer: str = ''


@dataclass(frozen=True, slots=True)
class Negation(Op):
  '''(negation #:schema R #:ver V #:index (R cols...) #:prefix (...))'''

  rel_name: str
  version: Version
  index: list[int]
  prefix_vars: list[str] = field(default_factory=list)
  const_args: list[tuple[int, int]] = field(default_factory=list)
  handle_start: int = -1


@dataclass(frozen=True, slots=True)
class InsertInto(Op):
  '''(insert-into #:schema R #:ver V #:dedup-index (cols...) #:terms (vars))'''

  rel_name: str
  version: Version
  vars: list[str]
  index: list[int]  # dedup index columns


# -----------------------------------------------------------------------------
# Pragma wrap ops (inserted by MirPragmaPass — Phase C)
# -----------------------------------------------------------------------------
#
# Wrap ops materialize a typed `Pragma` instance into the MIR tree. Each
# wrap op corresponds to one `Pragma` subclass; `MirPragmaPass` walks
# the registered `@pragma_handler` callbacks and replaces the bare op
# the pragma was attached to with the wrap-op-decorated form. The
# wrap op's lowering then emits the codegen specialization that was
# previously gated by an `if ctx.<pragma>:` branch in the imperative
# lowerings.
#
# Per `docs/phase_c_pragma_materialization.md` §2.1 (worked example
# for `dedup_hash` -> `DedupGate`) and `docs/pragma_as_typed_object.md`
# §3 (the `@pragma_handler` contract that produces them).


@final
@dataclass(frozen=True, slots=True)
class DedupGate(Op):
  '''MIR wrap op: dedup-hash gate around an emission op.

  Inserted by `srdatalog.ir.dialects.relation.sorted_array.pragmas.
  dedup_hash.materialize_dedup_hash` during `MirPragmaPass` whenever
  an `ExecutePipeline` carries a `DedupHash` pragma. Lowered by the
  `@lowering(target=iir.cf, source=DedupGate)` rule registered in
  the same module to the same IIR shape that the legacy
  `ctx.dedup_hash` branch inside `_lower_insert_into` produces.

  The wrap op carries the inner `InsertInto` so the lowering has
  everything it needs (vars, rel_name, index) to emit the
  `try_insert(thread_id, vars...) + if (_p) { write }` gate.

  Phase C scope (per spec §2.1 + §4.3): the gate lives in MIR (not
  IIR) because the materialized form is "wrap the InsertInto" — a
  per-emission decoration, structurally an MIR-level concern that
  the MIR -> IIR lowering then translates.
  '''

  inner: InsertInto


@final
@dataclass(frozen=True, slots=True)
class WSScope(Op):
  '''MIR wrap op: work-stealing scope around an emission op.

  Inserted by `srdatalog.ir.dialects.parallel.atomic_ws.pragmas.
  work_stealing.materialize_work_stealing` during `MirPragmaPass`
  whenever an `ExecutePipeline` carries a `WorkStealing` pragma.
  Lowered by the `@lowering(target=iir.cf, source=WSScope)` rule
  registered by the `parallel.atomic_ws` sub-dialect to the same IIR
  shape that the legacy `ctx.ws_enabled` branch inside
  `_lower_insert_into` produces (count-phase `<out>++` instead of
  `<out>.emit_direct()`).

  The wrap op carries the inner `InsertInto` so the lowering has
  everything it needs to emit the WS-count increment / pass-through
  the materialize-phase write. The runner-level WS scaffolding
  (WCOJTask queue + steal loop) is out of C4 scope per
  `docs/phase_c_pragma_materialization.md` §5 (PR row C4); this op
  covers only the kernel-functor-level WS emit variant that the
  legacy `ws_enabled` flag drives in `_lower_insert_into`.

  Per spec §4.2, this op lives in the new `parallel.atomic_ws`
  sub-dialect's lowering surface; the type itself lives here in
  `mir/types.py` next to `DedupGate` so all MIR wrap ops are
  discoverable in one place (matching the C2 placement).
  '''

  inner: InsertInto


# -----------------------------------------------------------------------------
# Fixpoint maintenance ops (scalar — no children)
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class RebuildIndex(Op):
  '''(rebuild-index #:index (R cols...) #:ver V)'''

  rel_name: str
  version: Version
  index: list[int]


@dataclass(frozen=True, slots=True)
class ClearRelation(Op):
  '''(clear-relation #:schema R #:ver V)'''

  rel_name: str
  version: Version


@dataclass(frozen=True, slots=True)
class CheckSize(Op):
  '''(check-size #:schema R #:ver V)'''

  rel_name: str
  version: Version


@dataclass(frozen=True, slots=True)
class ComputeDelta(Op):
  '''(compute-delta #:schema R)'''

  rel_name: str
  index: list[int] = field(default_factory=list)  # canonical index cols


@dataclass(frozen=True, slots=True)
class ComputeDeltaIndex(Op):
  '''(compute-delta-index #:schema R #:canonical-index (cols...))'''

  rel_name: str
  canonical_index: list[int]


@dataclass(frozen=True, slots=True)
class MergeIndex(Op):
  '''(merge-index #:index (R cols...))'''

  rel_name: str
  index: list[int]


@dataclass(frozen=True, slots=True)
class MergeRelation(Op):
  '''(merge-relation #:schema R)'''

  rel_name: str


@dataclass(frozen=True, slots=True)
class RebuildIndexFromIndex(Op):
  '''(rebuild-index-from-index #:source (R cols...) #:target (R cols...) #:ver V)'''

  rel_name: str
  source_index: list[int]
  target_index: list[int]
  version: Version


# -----------------------------------------------------------------------------
# Structural ops
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ExecutePipeline(Op):
  '''(execute-pipeline #:rule N #:sources (tuple ...) #:dests (tuple ...) <body>)

  Phase A change: gains `pragmas: tuple[tuple[str, Any], ...]` field
  (open key/value list, typed as tuple from the start). The existing
  named bool fields stay for back-compat through Phase A and are
  removed in Phase A3.

  In Phase C, `MirPragmaPass` consumes `pragmas` (not the named bool
  fields) — the named bools are deprecated migration sugar.
  '''

  pipeline: list[MirNode]
  # column-source / scan / negation / aggregate leaves for scheduler
  source_specs: list[Union[ColumnSource, Scan, Negation, Aggregate]]
  dest_specs: list[InsertInto]  # insert-into targets
  rule_name: str = ''
  clause_order: list[int] = field(default_factory=list)
  pragmas: tuple[tuple[str, Any], ...] = ()  # Phase A: open key/value list
  use_fan_out: bool = False  # back-compat: removed in A3
  work_stealing: bool = False
  block_group: bool = False
  dedup_hash: bool = False
  count: bool = False
  concurrent_write: bool = False


@dataclass(frozen=True, slots=True)
class FixpointPlan(Op):
  '''(fixpoint-plan <instructions...>)'''

  instructions: list[MirNode]
  schema_arities: list[tuple[str, int]] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class Block(Op):
  '''(block <instructions...>)'''

  instructions: list[MirNode]


@dataclass(frozen=True, slots=True)
class BalancedScan(Op):
  '''(balanced-scan #:group-var v #:source1 (...) #:source2 (...))

  Pre-computes a work-distribution histogram for a skewed join: partition
  work across (source1 × source2) pairs grouped by `group_var` (the
  "balanced root"). Emitted by lowering when a rule's plan specifies
  `balanced_root` + `balanced_sources`.
  '''

  group_var: str
  source1: ColumnSource
  source2: ColumnSource
  vars1: list[str] = field(default_factory=list)
  vars2: list[str] = field(default_factory=list)
  handle_start: int = -1


@dataclass(frozen=True, slots=True)
class PositionedExtract(Op):
  '''(positioned-extract #:var v #:sources ((...) (...)) #:bind (...))

  After a BalancedScan binds its group variable, any subsequent ColumnJoin
  for that variable becomes a positioned extract: point-lookup rather than
  iteration.
  '''

  sources: list[ColumnSource]
  var_name: str
  bind_vars: list[str] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class ParallelGroup(Op):
  '''(parallel-group <ops...>) — independent ops that can run concurrently.'''

  ops: list[MirNode]


@dataclass(frozen=True, slots=True)
class InjectCppHook(Op):
  '''(inject-cpp-hook #:rule R #:code "...") — raw C++ injection point.

  The Nim emitter prints #:code "..." without the actual code body (just
  the ellipsis), matching debug/tooling display; real content stays in
  the node's code field for codegen.
  '''

  code: str
  rule_name: str = ''


@dataclass(frozen=True, slots=True)
class PostStratumReconstructInternCols(Op):
  '''(post-stratum-reconstruct-intern-cols #:rel R #:canonical-index (cols...))

  Emitted once per stratum per relation: single cleanup step that replaces
  a per-index RebuildIndex loop, pushing complexity into the C++ runtime.
  '''

  rel_name: str
  canonical_index: list[int]


@dataclass(frozen=True, slots=True)
class Program(Op):
  '''(program (step #:recursive b <plan>) ...)'''

  steps: list[tuple[MirNode, bool]]  # (plan, is_recursive)


# -----------------------------------------------------------------------------
# Union type and convenience
# -----------------------------------------------------------------------------

MirNode = Union[
  ColumnSource,
  Scan,
  ColumnJoin,
  CartesianJoin,
  Filter,
  ConstantBind,
  Negation,
  Aggregate,
  CreateFlatView,
  InnerPipeline,
  ProbeJoin,
  GatherColumn,
  InsertInto,
  DedupGate,
  WSScope,
  RebuildIndex,
  ClearRelation,
  CheckSize,
  ComputeDelta,
  ComputeDeltaIndex,
  MergeIndex,
  MergeRelation,
  RebuildIndexFromIndex,
  ExecutePipeline,
  FixpointPlan,
  Block,
  ParallelGroup,
  BalancedScan,
  PositionedExtract,
  InjectCppHook,
  PostStratumReconstructInternCols,
  Program,
]
